name: OCRTrainer
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.12.1
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.3.2
  - comm=0.2.3
  - contourpy=1.3.1
  - cpuonly=2.0
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=13.0.85
  - cuda-runtime=12.1.0
  - cuda-version=13.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - ffmpeg=6.1.1
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.7.0
  - intel-openmp=2023.0.0
  - ipykernel=7.0.1
  - ipython=8.37.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - kiwisolver=1.4.8
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - leptonica=1.82.0
  - lerc=4.0.0
  - libarchive=3.8.2
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.15.1.6
  - libcups=2.4.2
  - libcurand=10.4.0.35
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.22
  - libdrm=2.4.124
  - libegl=1.7.0
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgl=1.7.0
  - libglib=2.84.4
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libkrb5=1.21.3
  - libllvm15=15.0.7
  - libnpp=12.0.2.50
  - libnsl=2.0.0
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libogg=1.3.5
  - libopengl=1.7.0
  - libopenjpeg=2.5.4
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libsodium=1.0.20
  - libstdcxx-ng=11.2.0
  - libtheora=1.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.2.1
  - mesalib=25.1.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - natsort=8.4.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numexpr=2.11.0
  - ocl-icd=2.3.2
  - openh264=2.6.0
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.0.18
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=5.9.1
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pygments=2.19.2
  - pyparsing=3.2.0
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwayland=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - readline=8.3
  - requests=2.32.5
  - sip=6.12.0
  - six=1.17.0
  - spirv-tools=2025.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - sympy=1.14.0
  - tbb=2021.8.0
  - tesseract=5.2.0
  - tk=8.6.15
  - tomli=2.2.1
  - torchaudio=2.4.0
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wayland=1.24.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - aistudio-sdk==0.3.8
      - annotated-types==0.7.0
      - anyio==4.11.0
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrdict==2.0.1
      - attrs==25.4.0
      - babel==2.18.0
      - bce-python-sdk==0.9.60
      - beautifulsoup4==4.14.3
      - blinker==1.9.0
      - cachetools==7.0.1
      - cfgv==3.5.0
      - chardet==5.2.0
      - click==8.3.0
      - colabcode==0.1.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.10.1
      - cssselect==1.4.0
      - cssutils==2.11.1
      - cython==3.2.4
      - datasets==4.4.1
      - dill==0.4.0
      - distlib==0.4.0
      - easyocr==1.7.2
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - filelock==3.20.0
      - filetype==1.2.0
      - fire==0.7.1
      - flask==3.1.2
      - flask-babel==4.0.0
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - future==1.0.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface==0.0.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - identify==2.6.15
      - imageio==2.37.2
      - imagesize==1.4.1
      - imgaug==0.4.0
      - itsdangerous==2.2.0
      - jiwer==4.0.0
      - joblib==1.5.2
      - kintera==1.3.0
      - lazy-loader==0.4
      - levenshtein==0.27.3
      - lmdb==1.7.5
      - lxml==6.0.2
      - markupsafe==3.0.3
      - ml-dtypes==0.5.4
      - modelscope==1.34.0
      - more-itertools==10.8.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - ninja==1.13.0
      - nltk==3.9.2
      - nodeenv==1.9.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.6.77
      - onnx==1.19.1
      - onnx-ir==0.1.12
      - onnxruntime==1.23.2
      - onnxscript==0.5.6
      - onnxslim==0.1.74
      - opencv-contrib-python==4.6.0.66
      - opencv-python==4.13.0.92
      - openpyxl==3.1.5
      - opt-einsum==3.3.0
      - pdf2docx==0.5.8
      - pillow==10.4.0
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - pre-commit==4.5.0
      - premailer==3.10.0
      - prettytable==3.17.0
      - propcache==0.4.1
      - protobuf==6.33.1
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pyclipper==1.4.0
      - pycryptodome==3.23.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pydisort==1.4.5
      - pyharp==1.8.8
      - pymupdf==1.27.1
      - pyngrok==7.4.1
      - pypdfium2==4.30.0
      - python-bidi==0.6.7
      - python-docx==1.2.0
      - python-dotenv==1.2.1
      - python-levenshtein==0.27.3
      - rapidfuzz==3.14.3
      - rarfile==4.2
      - regex==2025.10.23
      - ruamel-yaml==0.19.1
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - setuptools==80.9.0
      - shapely==2.1.2
      - snapy==1.2.9
      - sniffio==1.3.1
      - soupsieve==2.8.3
      - surya-ocr==0.17.0
      - termcolor==3.3.0
      - tifffile==2025.5.10
      - tokenizers==0.22.1
      - torch==2.7.0
      - torchvision==0.22.0
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.3.0
      - typing-inspection==0.4.2
      - ujson==5.11.0
      - virtualenv==20.35.4
      - visualdl==2.5.3
      - werkzeug==3.1.5
      - xxhash==3.6.0
      - yarl==1.22.0
