path: c:\Users\Nikunj\Desktop\Code\NepaliDevanagariVision\Object_Detection\data
train: images/train
val: images/val
test: images/test
nc: 1
names:
  0: line
task: detect
model: yolov8n.pt
epochs: 100
batch: 16
imgsz: 960
lr0: 0.01
optimizer: SGD
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
flipud: 0.0
fliplr: 0.5
rect: true
pad: true
